name: polypdiag
root: ${oc.env:STOMP_POLYPDIAG_DATA,data/downstream/polypdiag}
split: train
num_classes: 2
normalization:
  mean: [0.45, 0.45, 0.45]
  std: [0.225, 0.225, 0.225]
with_index: False

mode: train
num_clips_from_video: 1
num_crops_from_clip: 1
num_frames_from_crop: 8
sampling_rate: 8
target_fps: 30.0
multithread_decode: False
decoding_backend: pyav
num_retries: 10
